#!/usr/bin/env bash
#This script displays the username, user id and user home directory path of the file /etc/passwd

while IFS=: read -r username _ userid home_directory _; do
  echo "$username:$userid:$home_directory"
done < /etc/passwd
