#!/usr/bin/env bash
#This script displays the time for 12 hours and 59 minutes, display hours from 0 to 12 and display minutes from 1 to 59

hours=0
while [ $hours -le 12 ]; do
    minutes=1
    while [ $minutes -lt 60 ]; do
        echo "$hours hours and $minutes minutes"
        minutes=$((minutes + 1))
    done
    hours=$((hours + 1))
done
