#!/usr/bin/env bash
#This script displays the PID, along with the process name, of processes whose name contain the word bash
# shellcheck disable=SC2009

for pid in /proc/[0-9]*; do
    if [[ -e "$pid/comm" ]]; then
        process_name=$(cat "$pid/comm")
        if [[ $process_name == *bash* ]]; then
            echo "$(basename "$pid") $process_name"
        fi
    fi
done


