#!/usr/bin/env bash
#This script stops the 4-to_infinity_and_beyond process

pid=$(pgrep -f "infinity_and_beyond")

if [[ -n $pid ]]; then
    kill "$pid"
    echo "Process $pid has been stopped."
else
    echo "No process found with 'infinity_and_beyond'."
fi
