#!/usr/bin/env bash
#This script stops the 4-to_infinity_and_beyond process

pid=$(pgrep -f "To infinity and beyond")

if [[ -n $pid ]]; then
    kill "$pid"
    echo "Process $pid has been stopped."
else
    echo "No process found displaying 'To infinity and beyond'."
fi
